LEFT_EYE = [263, 387, 385, 362, 380, 373]
RIGHT_EYE = [33, 160, 158, 133, 153, 144]
LIP = [11,16] #centers of upper lip and lower lip
FOCUS_POINTS = [1, 199, 263, 33, 291, 61]
## focus points for head pose estimation:
## nose, chin, left corner of left eye, right corner of right eye, left corner of mouth,
## right corner of mouth
FACE = [10, 175]

THRESHOLD_RIGHT_Y = 12
THRESHOLD_RIGHT_Z = 20
THRESHOLD_LEFT_Y = -12
THRESHOLD_LEFT_Z = -20
THRESHOLD_UP_X = 20
THRESHOLD_DOWN_X = -5

FPS = 20
FILE_OUTPUT = "output.avi"
THRESHOLD_YAWN = 0.2
THRESHOLD_YAWN_TIME = 2
THRESHOLD_TALKING_MIN = 0.1
THRESHOLD_TALKING_MAX = 0.2
THRESHOLD_TALKING_TIME = 5
THRESHOLD_EYE_DIRECTION_MIN = 0.8
THRESHOLD_EYE_DIRECTION_MAX = 1.0
THRESHOLD_EYE_DIRECTION_TIME = 5
THRESHOLD_EYE_OPENNESS = 0.25
THRESHOLD_EYE_OPENNESS_DROWSINESS_TIME = 5
THRESHOLD_EYE_OPENNESS_SLEEPING_TIME = 30
THRESHOLD_HEAD_LOOKING_AWAY_TIME_1 = 5
THRESHOLD_HEAD_LOOKING_AWAY_TIME_2 = 60
THRESHOLD_NO_FACE_TIME = 10 
